[debian]
k3s      ansible_host=192.168.1.10  ansible_user=erebe
toybox   ansible_host=192.168.1.11  ansible_user=erebe
mail     ansible_host=192.168.1.13  ansible_user=erebe
dns      ansible_host=192.168.1.2   ansible_user=erebe
server   ansible_host=erebe.eu      ansible_user=erebe
proxmox  ansible_host=192.168.1.4   ansible_user=root

[router]
router   ansible_host=192.168.1.1   ansible_user=root

[nodes:children]
debian
router

[nodes:vars]
#ansible_become=true
#ansible_become_method=sudo
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=auto_silent
