[nodes]
k3s      ansible_host=192.168.1.10  ansible_user=erebe
toybox   ansible_host=192.168.1.11  ansible_user=erebe
mail     ansible_host=192.168.1.13  ansible_user=erebe
dns      ansible_host=192.168.1.2   ansible_user=erebe
server   ansible_host=erebe.eu      ansible_user=erebe  ansible_python_interpreter=/usr/bin/python3.13
router   ansible_host=192.168.1.1   ansible_user=root  ansible_python_interpreter=/usr/bin/python3.9
proxmox  ansible_host=192.168.1.4   ansible_user=root

[nodes:vars]
ansible_become=true
ansible_become_method=sudo
