apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
labels:
  - includeSelectors: false
    pairs:
      app: karakeep
resources:
  - namespace.yaml
  - service-chrome.yaml
  - service-meilisearch.yaml
  - service-web.yaml
  - pvc-data.yaml
  - pvc-meilisearch.yaml
  - deployment-chrome.yaml
  - deployment-meilisearch.yaml
  - deployment-web.yaml
  - httproute.yaml
configMapGenerator:
  - name: karakeep-configuration
    literals:
      - KARAKEEP_VERSION=release
      - NEXTAUTH_URL=http://localhost:3000
generators:
  - secret-generator.yaml
