apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: karakeep-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /opt/kustomize/ksops
files:
  - ../secrets/karakeep.yml
