apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: versitygw-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /opt/kustomize/viaduct.ai/v1/ksops/ksops
files:
  - ../secrets/versitygw.yml
