apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pv-claim
spec:
  storageClassName: zfs-nfs-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
