apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-backup
spec:
  schedule: "0 5 * * *" 
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - minio
          containers:
          - name: backup
            image: alpine
            args:
            - /bin/sh
            - -c
            - apk add --no-cache curl rclone; cd /tmp_dir;
             rclone config create dedibox-backup ftp host=dedibackup-dc3.online.net user=${FTP_USER} pass=$(rclone obscure ${FTP_PASSWORD}) ;
             rclone config create minio s3 provider=Minio env_auth=false access_key_id=${S3_USER} endpoint=http://localhost:9000  secret_access_key=${S3_PASSWORD} ;
             rclone copy --progress dedibox-backup:/backups/backup.tar.zst.enc minio://backup/ &&
             curl https://hc-ping.com/93721aa2-4037-45f7-8e6f-9218b9a1d1ef
            env:
            - name: FTP_USER
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: username
            - name: FTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: password
            - name: S3_USER
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: username
            - name: S3_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: password
            volumeMounts:
            - name: tmp-dir
              mountPath: /tmp_dir
          restartPolicy: OnFailure
          volumes:
          - name: tmp-dir
            emptyDir: {}
          tolerations:
          - key: "kubernetes.io/hostname"
            operator: "Equal"
            value: "minio"
            effect: "NoSchedule"
