apiVersion: ENC[AES256_GCM,data:bAA=,iv:Q5J8FbJk4WR6ENvf6N7x7AIeiImomPU3D/n60l3PjgQ=,tag:DAyv4ajzM7cZ1I5Vhmxi5g==,type:str]
kind: ENC[AES256_GCM,data:TxbyzOsE,iv:e7+TzF1SMULHPtMTbbl6EaWsfPyXJEytm1yKO1vNxjM=,tag:Wp5BX/wjcCUw0j3PYgcDgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VmCE/GTt9wIDV88=,iv:IFINSjcPAksWrEQwYpbMWlx5GYwMoCNBBEFiDFid0EQ=,tag:nJhaj0ZCsyklK+FuZshPUw==,type:str]
    namespace: ENC[AES256_GCM,data:tGDD/vEF2ukp0dFfOw==,iv:5QK9LyKb7s9HIahHRjF96NhnUbflQUo1EKQih54/Bfg=,tag:TCXTT+v1XN0MUbttAYMH/g==,type:str]
type: ENC[AES256_GCM,data:IjEgfPL8,iv:ANEJbSKzWbIcvefsR4TY0UuZYxc0aLjNYDtQwNXsW9Q=,tag:JozA/c4PA1b7AcRBZexEUg==,type:str]
stringData:
    server-auth-token: ENC[AES256_GCM,data:agk/aTP3E/NY3/xYufZvYduxQdQJ7+3S93tSMYu7usoMyRHHajjc5w==,iv:aS9sKR0YwLdyiS/IyXBKrSZ/5eUB+LbsE+5aFeeyTAs=,tag:eFxdzAKgQZyfYPvNGnPpHg==,type:str]
sops:
    lastmodified: "2026-09-07T22:12:47Z"
    mac: ENC[AES256_GCM,data:UNFPRapGptCqhn1uPDFjujSijM6Pv8i0OekR0x8FHBFVZdW3xe2TLlnRYTzN0EocenxUQ96WOZFfpHObticQ4cpp8hLFrm/bc7yiYRXO2fIsil3ufkO7PYU0q3y1p7H7VGPi1gacjni1R0PJXL/2iG+aFP6VjDiMscO0fkTn3sk=,iv:JwItq0RYUE8c/6Euj8b6sKJ7MzqqyGyd5ODuAti0nYs=,tag:wzxQlkVxZB6AHS02mk52RA==,type:str]
    pgp:
        - created_at: "2026-09-07T22:12:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKAQ//VbJpI1IO8LcZlDiZrBAUY7XcGpQnm7uFk35nhw1gAz+C
            oXObstPytil58ailM6zEZap+5pWfY66BXU8xPEsN7us/6iPj+8+G4NzD5hpQYiiy
            R6clWEK5GErWLE9Pr2k3dCaKuF1h0/sePqj5H5Av+hIwEEXZCZvFdWy3KfBPbVtV
            YezljYdkNVKKwgZspKpixDAz3HkuVa4RWGkIcPnYHLwWxRK1HDre46GkdfkwveM6
            7QgOV/VwwBn1vW9nOTNwn/13BkSlhZnkGyu2A1RpEnpv4gVqWrDGXyRYqa2fL9Cv
            CCSGZt3zOcxmWgYb8At0jHnGoNDbtaqN3EMP15ymVw87BWtej1y7XdbIEiyETWqo
            L1WAejBIG6PURb6K8/8TUBuH/YuK1pQ3puMe468LTAs6x1/fnVjbluAaiVd1S5ZZ
            CXOmVgIXu4pW2LLjkvaZQnb1unzOOufnvaBQvbFmIPSIpNlYiXUZg0ctU3TdA3Vf
            h8+rqnIGsEHCp7G9knu7hcrcit4TN96/h2/y4Wk9f5qlNy6Z5CjR0vowAlXEdHfN
            piVyZGjfoK+92dYZ3OZm3rd6EOu/Uvn+6nAejPE+/5m32ve8ksQtZW9kjma9jG8E
            m0cvpVrUQLhyrZ+sORRqdGm6cr8l8hpO5T7zgJgvcbErZ7tLZivuqJq7n6Gms+zS
            UQFgih/W7/7QPWG2xixyM+lOgtavh7KFs+xShPlW+LpPheKH2Zog3S/avK9jgVQX
            4vrLrgQhg1h71H4hlEGk5cgAmK5sEr0XEzxGRkjYKWcpbg==
            =J125
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.13.3
