apiVersion: ENC[AES256_GCM,data:qMk=,iv:HTR9KKt5R/Ls8AJhGD1QPHIk3DJ64cueWQInDd0mA28=,tag:ekLZHlv2kQI7CgnuI4p2RA==,type:str]
kind: ENC[AES256_GCM,data:7uj4bYRL,iv:cLZcfeEMB0z0y7TllCK10pv9jIHDVOUQL5j0t+fyTqk=,tag:fQeBFhuu9/i72lxHdI7bMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nlDavBcjSWAHX85kjw==,iv:1zhT5+mAzHQfmMDxGQmhUJgZi0ePiLGnQ6F6J2nqGIQ=,tag:EWUd3S99cPkivsw39M1b7g==,type:str]
    namespace: ENC[AES256_GCM,data:UCdKFHxjfU5WH/QyMQ==,iv:LU7MLBg5SWTko6m7dfgDW65mUV0t5HA1A+600jxouVw=,tag:BIo/Wou3tw/1JBEXd4ww1A==,type:str]
type: ENC[AES256_GCM,data:fFs9XMW6,iv:+2ujzDDx4k+e4jkBwQeMUyZVKU9Kwa1l7Ldsl4yxZIg=,tag:kKwXm0yISEW6HMBylpOrfA==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:sTzasF0=,iv:VVxXlZKxpwTwKRBp7lVaPNBhOZQo++KYbvA92ejW2eo=,tag:KxvS49m+W2ivL+jZmx0N3A==,type:str]
    admin-password: ENC[AES256_GCM,data:y7gyO9AJMa6S93pALmk=,iv:qtepu4w4Y8BJHIYWib25dFARb84UvKslBKBeeVl8WGw=,tag:fiyoYoFjGjbdz0nwgh++sQ==,type:str]
sops:
    lastmodified: "2026-09-07T19:43:51Z"
    mac: ENC[AES256_GCM,data:S1p5oONTRAm4Lmd1eVZB3te452c6mq36/g1WfGjEOv0ty/jDD4IgBmyRtjlBSELufNpgITa33nvyZJs1cwIJGXWRBn4vetY/xGfzZGdNDzHbnuArIOksQB+CwZe/zkkyfsZi6RcjaapX7IrrEo/N/IrEH6W7S23Hoyq+MQ1qabk=,iv:VasygjINhzUgS7fUb5GNtrGhvvqsDrnmYVKb0/SsFTs=,tag:+SGo3y4fYYkcrt35eo5kNA==,type:str]
    pgp:
        - created_at: "2026-09-07T18:54:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKARAArzBNU0a3hFXCwBoqU2aG8cP16isc4qILsomXHnIDzq2m
            B6F7wOlqRj8uNvpHSEHRB0osiAjjC4nZBjfrRNxxu/lRUR+YGCnRCUXyPijtmTFl
            P0JryraHsQNHmTm5UtPl4vOxPOud0LkfyzFNX6dDBTIsSpZyevAsoPu2RwPMvJI1
            UEFyB844I1LqgZWDxu9LnRZfFBrQxwawMvJqN8te+ojw0d8WgzB6wGRu1D23xj/H
            rchSBdj9ELNf9FRntOLsoCZRAPBa32wwjNl32fmOQwl0doFOpFF9EgrgHMD0MOyQ
            bQCBZ9GALDebT52lk6owz7ErGVctCsBBv6meQ9a/85nkPoue+INvSHxRf1mTtJAS
            8NPX06qMVZ86QWqqMtcSOrHbc1Svb5a8FgH+e6DR+o677Cq56hks1Rhu6eoNO+aC
            zxMilIvpzhb2JJFKL6sIYAt/OnYRFmOxas6wQk0yrAIynUMvdqzZQEP67kg9T+cs
            qd8Tt0hoUqxrHZJ76de7zLV6qatyuPUD0E0mxX3AMheR43wj4lGY36gzOjV4pJAq
            DEvdU3TXyaZJXqE1XFPS7P64V1NO44/d2v4z46ck3GIgcHqYfzDtRI5O+THl0DMn
            uS+lnsJ5FEgDWD2wvxXvxbjpYHeyqcyjn2tCFnoUXQJ6QLS0RCNOchNRjL6tZ2zS
            UQHUC1ofNLgCmvsCJ3WEjM9j4VqREZUGTlYJAKD0G4poszOTxkOk/Ml1TvXuByD+
            iGTDc/9Y6/Sk8hru7cru0rHregNg6Mo4p7oZWoh4XiLsAA==
            =ZFQG
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.13.3
