apiVersion: ENC[AES256_GCM,data:28Q=,iv:z4v9VS4tyCSnrI8xRRpJPHnnB5iIm+92kG01OjFFHzY=,tag:l5RxzqEiTjBJ8r1aNLndug==,type:str]
kind: ENC[AES256_GCM,data:S1rqxfKp,iv:0D0aEjr1nzuVf6YR020CYV/0gL5NsEMpNigTGinnQjo=,tag:Ka53UyRfKt7TtvkaFfv/rg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9U+o+SkGkcu398Xb/yg/Cw==,iv:p6ps+Vavg/8j1gKgqmFaC2HuhMeeZyvGXTOE8cczQxI=,tag:C2mMB0M5pQyOxMEWfMgsJQ==,type:str]
    annotations:
        kustomize.config.k8s.io/needs-hash: ENC[AES256_GCM,data:t9/oBA==,iv:SaEW61bUihi19JaYo0wg10zIfNmnCIqipEhS9c8pWRg=,tag:DoFg0YoaJY5fDUJnjJ7+Og==,type:str]
type: ENC[AES256_GCM,data:jlxifeKG,iv:64w17MEUp8qksFUV5FEfTRKWndkv3x6xjgvUcrlC0ZI=,tag:raLnfN07R/Uq1n2xW1qbMg==,type:str]
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:V+syVHHKMnYBGYnkg8PCOg==,iv:4ebgGE9lFXEfNNjZv/lTfPTRRh7GuCHZUvfirKoXA4I=,tag:XF2wDIYLa1YuZoFg00MpTA==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:AXIRO0jgEcXI0e5BdO0HGagQAbbXNn2Dy2mVXA==,iv:6xqWeL1uGxjcQxUWY+ZcMGrKCI1OClGTGAh5Fw/EfYg=,tag:CaiSUZI7j4hx6aHO+k2y5A==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:GXZqFG9ld8G03WiPt9JETg==,iv:e8OzifzQUUUL2ZkO+ih+k/PRKLQb6DHhn0SKJdMEu84=,tag:iQzNobCv8dd7k5A3hOONpw==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:/ll5R0IMnF/CxST4N3q3PGHCkXFysoxaZYdlYg==,iv:/zqbF2C3uqJdyvIQMRzb1CQx0XUo4xa1MrTaBwSZ180=,tag:IqdgTWILg3s3KU7X59ZHAQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Vr3r43kJ16FIOWHM4zm3Exp6VYlHgNA6+cBDSjxuHa5pssdcv/aGKPoqY3ovrV1hle05DNdFabhgZRPnLSt2W8K5UKVUs7jhaw==,iv:72yVEG8Be3yd0yOjHkH+Rhn+hcalDeioZMx9yMuO4fQ=,tag:iI0U53sR9su/J1zbCpfDkQ==,type:str]
    INFERENCE_TEXT_MODEL: ENC[AES256_GCM,data:l7xLORqFnajIpJulctfYYJ40I8neZY/Z3G7texXLGFtv,iv:yPk1SU55UAJnp9CiBUCUqY9eXjvn2lYrLH3pRy67854=,tag:nH6LDELpguBtfbTeOVNuCQ==,type:str]
    INFERENCE_IMAGE_MODEL: ENC[AES256_GCM,data:LuoNgn2+Bbw71Km7Gjn/2QRP0SW3YnKS9U0=,iv:ue/iVp49zL4b4mHVYpyqO5SLlu//JiK9PpXobS7Pz1Q=,tag:9jYEFocBerUXafLBG6iGag==,type:str]
sops:
    lastmodified: "2026-04-26T13:18:53Z"
    mac: ENC[AES256_GCM,data:eJy3c2l66BNf1m4ufCGuWtuDLh6nI0h5Fdd4+9TstAgnWx0l9AXk4khFofIpV3b7GTKaTiH2WPqBOtzt93i73YMxip32HjKr/S+IMHb4L4moEb6jJnOoceCHdnC8hWCzQxHLLTVqP7kpzhfCwPGjiCN45MJ87S9VYqaafE8jdL0=,iv:LLgMHUlGJiRVxRHWpgjnPWzg24ZgP4lggcP+IMIB8b4=,tag:5p/Wck5poGi7CE4aYd2uSw==,type:str]
    pgp:
        - created_at: "2026-04-26T13:18:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKAQ/+LYWfnvqlQG7t1JnesD7mYhorL8UtbRtHkef5Usp8VRoH
            v9gTHOi22XGAuUFPFtvtrIX3vykvM66vo4XXmBNEkENnQj16xEomZPCdiPLjr3d1
            jZCRkn5qShUUkV7cZq6MVrc9d7debdFOJL/hmTpHR9ZtMOQYZRuSKOubkkpCvnol
            yTUCnOZbLplAKDAmydyBblh+QM5cdWOXBELnnoZ2LhgVRQCVrLMZ1q6i27lziwlV
            gwjm9mqERh+0Q6Gyy2az3sexkJs4VqVb4uNvfDQuR8glZ24rCea/msLhAQZL5h9z
            8RRIhM6NFbYxpbiY7PwQxQ4rrzCBWE6pdHLgs2tVT4sZCO6tieKv1Al4XYzmDury
            RaO4teXKsepspibbE8rH76OWngfostaVIJE6s4HEIUmtlkWryw3K5aFxPlR2nAH8
            0eBShg0oc3sa/yMcBF/LFsKBbBb2Zl9VVhSHC4wh8HhVfmNkUlR6etXMbbuK7otU
            NR4GPa3U8SpgO0StPpMUIkQu7MHLZRvnzPYyBgO2y+1Dcjk4C/G9bp8bzVSB6FIz
            /wxGCdohFqYtDBBVQKMXNYZWHbpjgJbqjU8y2chN0hhlWrUMTpIRGuCQem7Vmy8Q
            5OH6aB4mS7/5spXb+80jHS9N2c66pWObsohrNkZ8zSFLToKrDchmBXAo3PlwNpXS
            UQEi3JU0rT2iphmKwAv35QpAYs2tqJINv5NAc8GFoeo5274cscZBZBRU3JjvC3JW
            HZiE8Cp5g5axjnF5ho9X+2j0dI1Z2V2drg4V9sSVrq1luw==
            =q09W
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.12.2
