apiVersion: ENC[AES256_GCM,data:mMQ=,iv:CpPJxDr9Jo13rKjjBuvdLyVSsTSCSRCBxbtBsWsK24s=,tag:W3qr0aHHnr7RwFZ3ughV2w==,type:str]
kind: ENC[AES256_GCM,data:TIuFFiwV,iv:KMNA/2ywYh0u4MLB+0cTgOoetFuvnNmCZ0jokLIxvx8=,tag:DFN7/z0qYzwyGSzQI5WMtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GhNc9J8=,iv:uF8j4d4qTh11/WpYjA0dwxXjp4mhfIXdVJ13+GriRQA=,tag:nnxtv0hZAkh8wFfaAN1ITg==,type:str]
    annotations:
        kustomize.config.k8s.io/needs-hash: ENC[AES256_GCM,data:Gp8lZQ==,iv:+sov788e2eKaGs6Pzr6iMC8XJmiEiMOUPAFeIVJaKfY=,tag:R2zdj0h8VG7D1A8w1ly2hw==,type:str]
type: ENC[AES256_GCM,data:+H4vWvuk,iv:bBjRQFn4K9obZdQfyNOYNWLqrSYn8KpKoSCJrY3cFVs=,tag:2bsOMT7r9o6Alw5WSaF5ZQ==,type:str]
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:+CE4jEG9u7u+F/in874=,iv:vC6cTpdiCItXdvVntb2OhbrMXU3txnaLmS4cbQ6LLGM=,tag:PXUSbtz2PfpjVRRTSyHFIw==,type:str]
sops:
    lastmodified: "2026-04-26T14:03:50Z"
    mac: ENC[AES256_GCM,data:KLzEUDD7NWOZoaXGQfwJrKRGmSNsZhkyPG6U0WW/cs9XmMS4ZMUSKKRnxclBj+5ZcNxh1R2YwBo86NLizlZ0p8zvPD3o5y4a80payXmhPJRNe0/Uz5cB8rThJ/QlXmD9Rk/H3/jFvGiN2+Q1WWsodh1wQy6ijwHah+e27JKIFPw=,iv:SpdUrN7w4o5GyG4oJk6Oq+XAPRvmvAPmplDTQAr5r0o=,tag:S1DRhTcDF3zZBu8OufEkPA==,type:str]
    pgp:
        - created_at: "2026-04-26T14:03:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKARAAtYcAz9a/7hAlsOrX6TMraX20yQyhIho9PDeDB4YOBzdG
            psagtXlU+Ge+7FvAHZuUM+AyxT/MLgYSI/dtkpmWwzXu5T9EZ6nhSeHCJ0Hga3SI
            t7/sZinuLI9K3bj0xGDZgvnopilApjtd322UiCZDhju/IT4yUw/gTWazbZaT8WOQ
            Tb7iVfRvrID9BEcXEzWP/aXHoPXM5CxtzTQ82CU4iFimEtYgtCbdfz9gLBPEndJq
            qrw+XZbeHKEoniemT1YUkV5s7oZxWklMqvBzFlYUEGV5RVBSxGKnagDUeHi0InGW
            gOT3VrO8TFGG0aRVPgilYd6bJqu9tiY/l9AVdSMTNQVgWnWWj7kjygoIn1zjnl97
            XKVbvKJ3xb+yMvcjJuH/RzEIkLC062GOEobC7DqhvOk+yQ2ccHpekYsLI+yxepbF
            j5pHLp21s0+c1S189WdPeePh+pig1BDKpt07o+WWQ2iDntEp+gSQAq+h7drn71z3
            yi9jOzUNgyAbZHSUPC91tHdoChB4xBchQR9+qgpzfNdzJ5Gy+Xp+hMq3UyWacZYU
            8f/RMnty5gHp5NGoZXBM9ZzzVjmAZhej7JtaP1dOBIUmeCrTsl9vtIPMFEpK8WW3
            Hq9sGSgzmR/npl38sjZzI8DmDjDVneeea2lnxTK5CmRzkMdTrRTGGT9eO0BxBEXS
            UQH4sGXGOPP2RgQuWpurNtZH2N5JAmTePYaW45UVQwlTZ8NPPBN6sTXXl4G3Jfab
            8Y2yMUguQalw8LqAWtcLUMTB3T+zbiJ+uqxOlgQ9H9xc4g==
            =ngSC
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.12.2
