apiVersion: ENC[AES256_GCM,data:wlM=,iv:67Sl/+S1udxZET6/Zawd/QBQE8vudlrjNanuZCikGV0=,tag:4USoJQk+PmNjh5a+Rj+13A==,type:str]
kind: ENC[AES256_GCM,data:am3MEfBz,iv:aUJ+FPtOCzlLW1PDQjqVGx0SFnxUA3cYoZjWylsm7o0=,tag:TiA324ffHHhxtHm8Jiiqdg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M2qWDFtMJi1KkoObe9E=,iv:oBG8vDJItWMoigvelHToPEsbWdo4dfBQgxLtdWo30v0=,tag:LKqFMpweSAdRVw+UB2B8qg==,type:str]
    annotations:
        kustomize.config.k8s.io/needs-hash: ENC[AES256_GCM,data:2BtzrQ==,iv:H13rYvlPvFDLZtZ8WJdDX3dOYy3LK3w38PAkxhOZmZ8=,tag:JUozXfgxCFPiwmLSkkHKLg==,type:str]
type: ENC[AES256_GCM,data:WOA46VyV,iv:G/lym3TPG8brB99u2n/YuSCVC2N8TIQ6GsQrBHkpxHk=,tag:iaHaZwX/oZAN1Aigmm00wg==,type:str]
stringData:
    hook.json: ENC[AES256_GCM,data:j3fPhFVKGzjndsSZu1hL4mDbAmpAnJujrXf/tZZyLDvrTwIrdi+wfT7kgq/UPqpSzbOH/cstCDQR9POW2RAbVTrAG2mJbT4V4fHpKFPrgrzFo82Ig+uO7TXkzvtgO0SjIWdlxvASX8y6Ab89vNTICPS1i5Vdw4aagsYPVT/KWII/MMfR97RIlS7e+p1k1zpLdrpbCsmpyp5rpRWL3xmOqdbUJUPY/RKconW12Av0HaC0ynVrrYKxZmTKlCjQZ3JEn/6KqOIzAPpeUCApSl5ZaSLCB8Yqqy9kJ6W1jJ/qFWcp8OE467Rf/GX1zCELYjAu9m2cdqoCkhgKVRozVjfL5LuKlyby+aIF861lZDYgtsI0gjjR8pK2TSqW0FpOnEdYhfxV7By4va8eGVlPAoHd1mrXaAG79PjBVtpaRnLdTmblsP3+ZOHPMUmKXPQ6HdqWQ0GfWZ9UXvUFGv87SvwMhVPmnQ1GGOkxexcqNruFvprxeABqvrTjpvU4eLAqJw7Bifyq4K5x0eYUWHLo/gS2f+uevyCKoXhTLXrWDkbFpWT6Ukcy0x8mYmRbvkndc7IGkT8Zrf5x5QyR,iv:Jb2D5lgRzJLqqhdp6K7mBqZZUKjwQv/m/PjYarukyaw=,tag:zC9mE6YswabJxa+B8PZwAA==,type:str]
sops:
    lastmodified: "2026-04-26T14:09:56Z"
    mac: ENC[AES256_GCM,data:o1jKEHONOxPGbbMUbgthPA8gS6BKmCUDDLO6pLaDRba5U/ZpCw/7zIuA8OUegLySVhHwLBbxjAJczIWzvfSuXuGkW8oiJWtSYVPLcPgDlSQsAILpSPgC0HRbPRDP5QL45y/JyqD0pwhVROGpV3LTEsucttlsXknN4UI1cSh+RSg=,iv:LmeGs7+hWcIe2L7h6XWC/lgsQXIIKeMIe/015JGGg4Q=,tag:UEggAgon2EVSNj5WxqbxKQ==,type:str]
    pgp:
        - created_at: "2026-04-26T14:09:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKARAAjklnlK/4g+QoGuVW9HhAuAo0+DfGCE9IKnJuu2o/YNmX
            Wg8lYK/Krg9ccbrgf1kK9pnlZWadkOuyC5FgiCu2gszhgCEQvuY/5tI+HJYTltZo
            IstTJ3UUmjvJJPRan4AhNPMRRf3zsIIS0Kq+WDeJ9YFrY5VYOYhrzVOHMN47I2ra
            BpNwi5fY5xLmNLBgUAfaaL7HiWY9qLJV+Us9KbVshewtij8j3tYiVyk281j9Mig6
            TpLiFzHViSvKFPShM5Ov+qhzGNArtny4w/pK+iT1txQXskCWZiXKJ0QLhT2EHdXo
            Izgy5K3oqyzOzfBK20BCsv3JlUjDtQhKqmgJZvy5wslG9h3B4+ab4GdkSJct/UYU
            NKvbQWgBMC3n8EefKpTHpdqkDqvTMBl+W4AHyIuAkvOyC9ymkYo7imSfEZCQbHUq
            l0I2n9OTSPvaPDE6L3k4Qb8YA0nFuRayEsUHxCfWnE+AyHd+u5UG0LMyp79+cZx4
            dafiuW2vArxDJBO5Adsehjs1LgaPsqAJHVlmcI+A59GmL8c9L93V37PSWBJbsaDS
            chtxYR5AC6DJVqjpo++xWvue6iN6P3lvBXx6ETbvcwSP+X1tjYJVI7kmUgh4joCL
            sI4bE1vik5Npq9Df5Bm8ldEaoZGFAF7p1UGWzwy51coiNKLwzylrhtUCkaz0m9DS
            UQELC0VYutti/UieVCS/z3b7gAQI+lnfcl2wqdd6mrZZZw214uBicQDLrr5Qffyg
            dV3gnLiGBpmjrbzsTB8kY77kdRZH26EOCQZHtOm7qEYWOQ==
            =O+7X
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.12.2
