apiVersion: ENC[AES256_GCM,data:9tY=,iv:Ak6lHHZQxC8pUxccccomnDqEKLIvbPq6mrOyNXLuZU0=,tag:gCOv4SgHdfOBVDEz+yhmeQ==,type:str]
kind: ENC[AES256_GCM,data:xXv8qxv7,iv:Zg+YlGKcM3hz+2w9jsVnWNcXPCYxTc55AGEoYZtoZ0s=,tag:crCmglUlFXy4N187xJhKXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eU73z5T/wRU=,iv:Cr1G/CLn5zD3r4o+D4WzajcANu0El85FAfjbZY/lRCI=,tag:atEdXIlwA5zdUEOmlfUrCA==,type:str]
    annotations:
        kustomize.config.k8s.io/needs-hash: ENC[AES256_GCM,data:cvKrgg==,iv:eiYOR4AGy+GBly5zeH9ND0Yxzj2bpV/X3XLz+JZ1pm0=,tag:34GLXV++wileWISvPt9/Tg==,type:str]
type: ENC[AES256_GCM,data:UeryWTe3,iv:Vip6maDJ5uKPi3UQ+tjqwmExZ7XwuFyMzw3wx7OvnyI=,tag:mn5Am6PfTLs3STpMFigNww==,type:str]
stringData:
    restrictions.yaml: ENC[AES256_GCM,data:KKORfSAM48Y1Osct8hJYNtVgGUqAQcZ8whEhG67Po9ssA1K4bljwu/WKHk9R9gd6yMGQC0/VIlAb7p6hj0z2D5KoxQvf1b8Wl2A+lJQeJ6EroyWkYUwv321oi1ipShGyZkeihqGjvMgBe5XiF7xfPqtcCTNvPMJU36vVKHVK1jpD/uBFoSMp1w7f/ckBW29WMvL5hIoIlSS+zChVeGYPNCp6fbeeV6IzLxJyclNr66IlTN33JU+eUBLr1QQi4KkXwYreerTuvenvL6zmLxxvDUay2QIrDRGM6wVbum8PhCjly2Xu8vx+NMOcepQNBrjg31sU9s10Sioz7XC71TVRqHjNuQb/IDhL5hZugNcYhg2QtOX0IE6sngxWPaiy4VXYE2FQEETroLK0RtLpqF3R7oUMRuXSSlKqgXAOWXX/Mcx4csFGIsKeZJpE3ty1x5IzGWj0tlWkH61R6bq7QINPlFXkxcEMpi2bmpFk5GYXAJNS0xBWXrmObKZYVpa6xCETwvXs1DhrgZgmlExkyy3GOeVisXsgLBiSFWVZ5+5epTLEoicXi3e0GQRICu/UHT6B0yqL9g==,iv:AACKJGqsgAkAoICLxnJwRSLjExvmz86S31j4tpAc5V0=,tag:tLP/MYnCy6DhZa+qFElkNg==,type:str]
sops:
    lastmodified: "2026-04-26T13:24:34Z"
    mac: ENC[AES256_GCM,data:e7DDywmKPSeJNCq5ekoVlPSsIs0e+uKN+Vl0joxmysvgSq+B8DtJNUT0jA3nghZEVL0h3RrwFjX+TNBoKdUOXns3sowUJwNFd1pbj90rNO7+vuseaHYJUEEoxsHwi9ZpV9KcYakEvQX1o0awry6rC6wcBKcYl8kfuWYQsHRSEAA=,iv:Z+f7qrBlV+MdWmGkhAwOcbWfc63iN7PoK622pcQ3gYU=,tag:8vZrdptinTq/LnFHD44/HA==,type:str]
    pgp:
        - created_at: "2026-04-26T13:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKARAAkKO00AjmYBW+ud/lf1y8+2ozeNcOlyWpxzE2jPcWhQps
            oq+UmoguVGW2N90Hsll5J467obFotujO0tpjRSCrrlLpYpEm/M8T/amV9ibGCFfb
            cMCklnn5xpqfG9dCRDHu06xzHeTLtZQFCoGq6glS3WoB8pXgbCqUsZnzn8a/8dll
            /B7QwdMMCFmgxo9oKYSJ1A9jRQ5wIW9lVe4EH10Y52sUcjXOOoLLJAHVbkB+noca
            rTGb5kjznZkSbBDqIVKLIjZvidtD1u6cDQQii58cSzAHetRvXQpDAl4GJjgIMA+s
            Wd9fwQLE33WN+X1PRZxqoOiMARC3rvzGiuPl/xl/vd5jSl6YH1SmkGh/SkgNxEPa
            M26CEZEfHVgV5MyPsHl4Shso5eVn1NTsAL5tPkfXcSfR/QtDaf47l+Ws2qL5UTyw
            85ThfQXS/LHs7Vck37JlFFGZHEtmIUVVW5NnxBweRdCWHax4FW0N8Wqyu48Y2M2r
            BRIO7O3EX7e+4MZv4sgmY4TNVAumJLixvnvBcMppax6kj5zhA/3D/Q9qxHCerWwv
            gB+jr9/0O23AnH0+0qlDI1PR4W9AdLOfPeqFKTtPrsjZzw7c5CVsE3TURc6NsqOl
            Hcq0iCMa8BpNQs+paq3MVcrXuorU3uvW8Uvvew6ag1zBjHgtQHptDV9YLqcVE6fS
            UQH2m97pbC0oCH1H+sYwosIgviDHW9m2kE820iISny4dd2lxB5aXR4mgCFtVbEkJ
            mDYgoN66MQf9hCByv6yov/TvKEubrhFqH7mOwnowCQeUJQ==
            =CNgh
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.12.2
