apiVersion: ENC[AES256_GCM,data:9tY=,iv:Ak6lHHZQxC8pUxccccomnDqEKLIvbPq6mrOyNXLuZU0=,tag:gCOv4SgHdfOBVDEz+yhmeQ==,type:str]
kind: ENC[AES256_GCM,data:xXv8qxv7,iv:Zg+YlGKcM3hz+2w9jsVnWNcXPCYxTc55AGEoYZtoZ0s=,tag:crCmglUlFXy4N187xJhKXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eU73z5T/wRU=,iv:Cr1G/CLn5zD3r4o+D4WzajcANu0El85FAfjbZY/lRCI=,tag:atEdXIlwA5zdUEOmlfUrCA==,type:str]
    annotations:
        kustomize.config.k8s.io/needs-hash: ENC[AES256_GCM,data:cvKrgg==,iv:eiYOR4AGy+GBly5zeH9ND0Yxzj2bpV/X3XLz+JZ1pm0=,tag:34GLXV++wileWISvPt9/Tg==,type:str]
type: ENC[AES256_GCM,data:UeryWTe3,iv:Vip6maDJ5uKPi3UQ+tjqwmExZ7XwuFyMzw3wx7OvnyI=,tag:mn5Am6PfTLs3STpMFigNww==,type:str]
stringData:
    restrictions.yaml: ENC[AES256_GCM,data:UKTTBBVpQ5T5t3iBZmbua4LkHud80dDDyCIyOJ9tflAL9R4CsRlLQQdAZ9hV3xbOJ8P7hjvjvasVKa9MxUaP/1pV04Elp6YFA1XP+3iplfBMl5KGVyVOIz7sVLgIWYTv/gvV1yaPFTuIK4t52HPnVQdUKts5gGwZjCFPKUikLCovgJ3Ow7Oorycsb4LO1/khNyGl8QJ32htbTu5aSiRtPpmuaLnvBNcmZ9oEz5vWRGasJkes1Yn74sYEtfycUXhoIeITfwk9AZB4qnR0Qc8kiTB4zcT+VmIzsJcaC5zJYXSn8mPbIpUpWd2q2/UoMnqzlfdMRLKfpa+Fb9EMjE98kXFVfskRDn0yP3dryCW7oPabYVA3sWu7pUBkO9AOYqQqkewJLcfVUj16eObvfLLT8XrkQhbK1ovahyvr2slaYMtxum2syMYN9THFfdCtA3Yy5v/sVETISn3zEaO6/POVRlfEuO+0gO7hxgzKntEEMeQpVZZFSskdzzm/9yhnDZO2bLXC2wj0twHsVf8=,iv:fxUOZI/fCWlRqn1O9GuSeZUw7mjqyoVluJ32gc5GnLM=,tag:3MlxBq8SSsUKTUWvt7LG3w==,type:str]
sops:
    lastmodified: "2026-04-30T19:55:17Z"
    mac: ENC[AES256_GCM,data:v9SzaUmaDbp+mkfgHM2Lpj9ZnLwhYOGYJ1iF9biPud0mjTNZ3p8yAQ1aQAbdM60nZNSO5zhXol5rONU4Q3w4NAzHNWxQMGac34MafQTGnua96JbG7H+K0+W/II/VXur786KfHk25YoCzrBoFzu1w3obSuonINqBNgVqeTve33pI=,iv:RlQcQiOhVKarS3IaRUdiVD4PeXuebSbA8uYjKdIeNeA=,tag:V5TEQciT43tnbhpMjpy16A==,type:str]
    pgp:
        - created_at: "2026-04-26T13:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9B6IoTj4kvKARAAkKO00AjmYBW+ud/lf1y8+2ozeNcOlyWpxzE2jPcWhQps
            oq+UmoguVGW2N90Hsll5J467obFotujO0tpjRSCrrlLpYpEm/M8T/amV9ibGCFfb
            cMCklnn5xpqfG9dCRDHu06xzHeTLtZQFCoGq6glS3WoB8pXgbCqUsZnzn8a/8dll
            /B7QwdMMCFmgxo9oKYSJ1A9jRQ5wIW9lVe4EH10Y52sUcjXOOoLLJAHVbkB+noca
            rTGb5kjznZkSbBDqIVKLIjZvidtD1u6cDQQii58cSzAHetRvXQpDAl4GJjgIMA+s
            Wd9fwQLE33WN+X1PRZxqoOiMARC3rvzGiuPl/xl/vd5jSl6YH1SmkGh/SkgNxEPa
            M26CEZEfHVgV5MyPsHl4Shso5eVn1NTsAL5tPkfXcSfR/QtDaf47l+Ws2qL5UTyw
            85ThfQXS/LHs7Vck37JlFFGZHEtmIUVVW5NnxBweRdCWHax4FW0N8Wqyu48Y2M2r
            BRIO7O3EX7e+4MZv4sgmY4TNVAumJLixvnvBcMppax6kj5zhA/3D/Q9qxHCerWwv
            gB+jr9/0O23AnH0+0qlDI1PR4W9AdLOfPeqFKTtPrsjZzw7c5CVsE3TURc6NsqOl
            Hcq0iCMa8BpNQs+paq3MVcrXuorU3uvW8Uvvew6ag1zBjHgtQHptDV9YLqcVE6fS
            UQH2m97pbC0oCH1H+sYwosIgviDHW9m2kE820iISny4dd2lxB5aXR4mgCFtVbEkJ
            mDYgoN66MQf9hCByv6yov/TvKEubrhFqH7mOwnowCQeUJQ==
            =CNgh
            -----END PGP MESSAGE-----
          fp: B3C25F146073BF8435E2A94A7A42B4B97E0332F4
    unencrypted_suffix: _unencrypted
    version: 3.12.2
