apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: wstunnel
resources:
  - deployment.yaml
  - service.yaml
  - tlsroute.yaml
generators:
  - secret-generator.yaml
