apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: wstunnel-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /opt/kustomize/ksops
files:
  - ../secrets/wstunnel.yml
