apiVersion: apps/v1
kind: Deployment
metadata:
  name: wstunnel
  labels:
    app: wstunnel
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: wstunnel
  template:
    metadata:
      labels:
        app: wstunnel
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "kubernetes.io/hostname"
        operator: "Equal"
        value: "server"
      containers:
      - name: wstunnel
        image: ghcr.io/erebe/wstunnel:latest
        imagePullPolicy: Always
        args:
        - "./wstunnel"
        - "server"
        - "wss://[::]:8084"
        - "--dns-resolver=dns://[fd00:cafe::2]"
        - "--restrict-config=/etc/wstunnel/restrictions.yaml"
        ports:
        - containerPort: 8084
        volumeMounts:
          - name: wstunnel
            mountPath: /etc/wstunnel
            readOnly: true
      volumes:
      - name: wstunnel
        secret:
          secretName: wstunnel
---
apiVersion: v1
kind: Service
metadata:
  name: wstunnel
spec:
  selector:
    app: wstunnel
  ports:
    - protocol: TCP
      port: 8084
      name: http
  clusterIP: None
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: wstunnel
spec:
  parentRefs:
    - name: envoy
      sectionName: tls-passthrough
  hostnames:
    - "ws.erebe.eu"
  rules:
    - backendRefs:
        - name: wstunnel
          port: 8084
