set dotenv-load := false

_default:
    @just --list

email:
	sops -d --output secrets_decrypted/dovecot.yml secrets/dovecot.yml
	sops -d --output secrets_decrypted/fetchmail.yml secrets/fetchmail.yml
	kubectl delete -f secrets_decrypted/dovecot.yml
	kubectl delete -f secrets_decrypted/fetchmail.yml
	kubectl delete -f email/deployment.yml
  

nextcloud:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone nextcloud/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/nextcloud-applyset --namespace=default


nextcloud_resync_file:
	kubectl exec -t $(shell kubectl get pods -n default -l app=nextcloud -o json | jq .items[].metadata.name) -- /usr/bin/occ files:scan --all


backup:
	sops -d --output secrets_decrypted/backup_credentials.yml secrets/backup_credentials.yml
	kubectl apply -f secrets_decrypted/backup_credentials.yml
	kubectl apply -f backup/backup-cron.yml
	kubectl apply -f backup/backup-minio.yml

webhook:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone webhook/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/webhook-applyset --namespace=default

wstunnel:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone wstunnel/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/wstunnel-applyset --namespace=default

coub:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone coub/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/coub --namespace=default

karakeep:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone karakeep/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/karakeep-applyset --namespace=karakeep

lb:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone lb/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/lb-applyset --namespace=default

stalwart:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone stalwart/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/stalwart-applyset --namespace=default

warpgate:
	kubectl apply -f app/warpgate.yml

blog:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone blog/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/blog-applyset --namespace=default

dashy:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone dashy/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/dashy-applyset --namespace=default

adguard:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone adguard/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/adguard-applyset --namespace=default

vaultwarden:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone vaultwarden/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/vaultwarden-applyset --namespace=default

minio:
	kustomize build --enable-alpha-plugins --enable-exec --load-restrictor LoadRestrictionsNone minio/ | KUBECTL_APPLYSET=true kubectl apply -f - --server-side --prune --applyset=configmaps/minio-applyset --namespace=default
