apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
  - postgres.yaml
patches:
  - target:
      kind: Deployment
      name: .*
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: kubernetes.io/hostname
            operator: Equal
            value: toybox
            effect: NoSchedule
