apiVersion: v1
stringData:
  username: app
  password: 3J8rYj8nMi2W
kind: Secret
metadata:
  name: app-db-password
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-db-password
      localeCollate: 'en_US'
      localeCType: 'en_US'
  affinity:
    tolerations:
      - key: kubernetes.io/hostname
        operator: Equal
        value: toybox
        effect: NoSchedule
  storage:
    size: 1Gi
