#!/bin/bash

[ "$IFACE" != "enp1s0" ] || exit 0

# In order to get an IPv6 lease from online.net
sysctl -w net.ipv6.conf.enp1s0.accept_ra=2

# Allow traffic forwarding
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=1
