#!/bin/bash

[ "$IFACE" != "enp1s0" ] || exit 0

# In order to get an IPv6 lease from online.net
sysctl -w net.ipv6.conf.enp1s0.accept_ra=2

###########################
# IPv4
###########################
# Reset our custom chain
iptables -P INPUT ACCEPT
iptables -D INPUT -j USER_CUSTOM
iptables -F USER_CUSTOM
iptables -X USER_CUSTOM

iptables -N USER_CUSTOM

# Allow loopback interface
iptables -A USER_CUSTOM -i lo -j ACCEPT

# Allow wireguard interface
iptables -A USER_CUSTOM -i wg0 -j ACCEPT

# Allow already accepted connections
iptables -A USER_CUSTOM -p tcp  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A USER_CUSTOM -p udp  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A USER_CUSTOM -p icmp -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Accept incoming ICMP
iptables -A USER_CUSTOM -p icmp -j ACCEPT

# Allow ssh
iptables -A USER_CUSTOM -p tcp --dport 22 -j ACCEPT

# Allow http/https
iptables -A USER_CUSTOM -p tcp --dport 80 -j ACCEPT
iptables -A USER_CUSTOM -p tcp --dport 443 -j ACCEPT

# Allow SMTP and IMAP
iptables -A USER_CUSTOM -p tcp --dport 25 -j ACCEPT
iptables -A USER_CUSTOM -p tcp --dport 993 -j ACCEPT

# Allow wireguard
iptables -A USER_CUSTOM -p udp --dport 995 -j ACCEPT

# Allow kubernetes
#iptables -A USER_CUSTOM -p tcp --dport 6443 -j ACCEPT


# Add our custom chain
iptables -I INPUT 1 -j USER_CUSTOM

# DROP INCOMING TRAFFIC by default
iptables -P INPUT DROP


###########################
# IPv6
###########################
# Reset our custom chain
ip6tables -P INPUT ACCEPT
ip6tables -D INPUT -j USER_CUSTOM
ip6tables -F USER_CUSTOM
ip6tables -X USER_CUSTOM

ip6tables -N USER_CUSTOM

# Allow loopback interface
ip6tables -A USER_CUSTOM -i lo -j ACCEPT

# Allow wireguard interface
ip6tables -A USER_CUSTOM -i wg0 -j ACCEPT

# Allow already accepted connections
ip6tables -A USER_CUSTOM -p tcp  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A USER_CUSTOM -p udp  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A USER_CUSTOM -p icmp -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Accept incoming ICMP
ip6tables -A USER_CUSTOM -p icmp -j ACCEPT

# Allow ssh
ip6tables -A USER_CUSTOM -p tcp --dport 22 -j ACCEPT

# Allow http/https
ip6tables -A USER_CUSTOM -p tcp --dport 80 -j ACCEPT
ip6tables -A USER_CUSTOM -p tcp --dport 443 -j ACCEPT

# Allow SMTP and IMAP
ip6tables -A USER_CUSTOM -p tcp --dport 25 -j ACCEPT
ip6tables -A USER_CUSTOM -p tcp --dport 993 -j ACCEPT

# Allow wireguard
ip6tables -A USER_CUSTOM -p udp --dport 995 -j ACCEPT

# Allow kubernetes
#ip6tables -A USER_CUSTOM -p tcp --dport 6443 -j ACCEPT


# Add our custom chain
ip6tables -I INPUT 1 -j USER_CUSTOM

# DROP INCOMING TRAFFIC by default
ip6tables -P INPUT DROP
