apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {}
  template:
    metadata: {}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "kubernetes.io/hostname"
        operator: "Equal"
        value: "toybox"
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: nextcloud
        image: linuxserver/nextcloud:31.0.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: nginx-siteconfig
          mountPath: /defaults/nginx/site-confs/
        - name: data-nvme
          subPath: config
          mountPath: /config
        - name: data-nvme
          subPath: data
          mountPath: /data
        - name: data-hdd
          subPath: photos
          mountPath: /data/cecile/files/photos
        - name: preview
          mountPath: /data/appdata_ocxf7jgp27m7/preview
      volumes:
      - name: nginx-siteconfig
        configMap:
          name: nextcloud-nginx-siteconfig
      - name: preview
        hostPath:
          path: /opt/nextcloud/preview
          type: Directory
      - name: data-nvme
        persistentVolumeClaim:
          claimName: nextcloud-pv-claim
      - name: data-hdd
        persistentVolumeClaim:
          claimName: nextcloud-hdd-pv-claim
