rules:
- listen_addr: 
    - "[::]:25"
    - "[::]:587"
  protocol: Tcp
  upstreams:
    - name: smtp
      match: !DestinationPort 25
      backends: !Static
        - addr: "[fd00:cafe::5]:25"
      proxy_protocol: true
      cnx_max_duration: 5m
      load_balancing: !RoundRobin

    - name: smtp
      match: !DestinationPort 587
      backends: !Static
        - addr: "[fd00:cafe::5]:25"
      proxy_protocol: true
      cnx_max_duration: 5m
      load_balancing: !RoundRobin

- listen_addr: 
    - "[::]:443"
  protocol: Tls
  upstreams:
    - name: wstunnel-demo
      match: !SniRegexNot \.erebe\.(dev|eu|eus)$
      backends: !Static
        - addr: "[fd00:cafe::254]:8084"
      proxy_protocol: false
      cnx_max_duration: 10s
      load_balancing: !RoundRobin

    - name: wstunnel
      match: !SniRegex ws\.erebe\.(dev|eu|eus)$
      backends: !Static
        - addr: "[fd00:cafe::254]:8084"
      proxy_protocol: false
      cnx_max_duration: 10s
      load_balancing: !RoundRobin

    - name: envoy-https
      match: !Any
      backends: !Static
        - addr: "10.43.0.11:444"
      proxy_protocol: true
      cnx_max_duration: 10m
      load_balancing: !RoundRobin
