apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: turbine-lb
resources:
  - deployment.yaml
configMapGenerator:
  - name: turbine-lb-config
    files:
      - config.yaml
