set dotenv-load := false

_default:
    @just --list

HOST := "erebe@127.0.0.1"

wireguard:
  sops exec-env ../../secrets/wireguard.yml 'cp wireguard/wg0.conf secrets_decrypted/; for i in $(env | grep _KEY | cut -d = -f1); do sed -i "s#__${i}__#${!i}#g" secrets_decrypted/wg0.conf ; done'
  sops exec-env ../../secrets/wireguard.yml 'cp wireguard/wgall.conf secrets_decrypted/; for i in $(env | grep _KEY | cut -d = -f1); do sed -i "s#__${i}__#${!i}#g" secrets_decrypted/wgall.conf ; done'
  sops exec-env ../../secrets/wireguard.yml 'cp wireguard/wgpub.conf secrets_decrypted/; for i in $(env | grep _KEY | cut -d = -f1); do sed -i "s#__${i}__#${!i}#g" secrets_decrypted/wgpub.conf ; done'
  ssh {{HOST}} "sudo cat /etc/wireguard/wg0.conf" | diff  - secrets_decrypted/wg0.conf || exit 0
  rsync --rsync-path="sudo rsync" secrets_decrypted/wg0.conf {{HOST}}:/etc/wireguard/wg0.conf
  rsync --rsync-path="sudo rsync" secrets_decrypted/wgall.conf {{HOST}}:/etc/wireguard/wgall.conf
  rsync --rsync-path="sudo rsync" secrets_decrypted/wgpub.conf {{HOST}}:/etc/wireguard/wgpub.conf
