apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: webhook
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
configMapGenerator:
  - name: webhook-scripts
    files:
      - deploy.sh
generators:
  - secret-generator.yaml
