apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: webhook-config
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /opt/kustomize/ksops
files:
  - ../secrets/webhook.yml
